# Generated by Django 3.1 on 2020-08-27 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateField(blank=True, verbose_name='date_paid(mm/dd/yy)')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('suite_number', models.IntegerField()),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^0?[5-9]{1}\\d{9}$')])),
            ],
        ),
    ]
